<?php

$config["school_list"] = array(
	array(
		"id" => "1",
		"url" => "1st-jh-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "15",
		"school"=> "東根市立第一中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "中学校"
	),
	array(
		"id" => "2",
		"url" => "2nd-jh-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "16",
		"school"=> "東根市立第二中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "中学校"
	),
	array(
		"id" => "3",
		"url" => "3rd-jh-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "17",
		"school"=> "東根市立第三中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "中学校"
	),
	array(
		"id" => "4",
		"url" => "ootomi-jh-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "18",
		"school"=> "東根市立大富中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "中学校"
	),
	array(
		"id" => "5",
		"url" => "jinmachi-jh-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "19",
		"school"=> "東根市立神町中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "中学校"
	),
	array(
		"id" => "6",
		"url" => "keyaki-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "5",
		"school"=> "東根市立東根小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "7",
		"url" => "tougo-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "6",
		"school"=> "東根市立東郷小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "8",
		"url" => "takasaki-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "7",
		"school"=> "東根市立高崎小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "9",
		"url" => "jinmachi-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "8",
		"school"=> "東根市立神町小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "10",
		"url" => "ootomi-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "10",
		"school"=> "東根市立大富小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "11",
		"url" => "odashima-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "11",
		"school"=> "東根市立小田島小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "12",
		"url" => "nagatoro-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "12",
		"school"=> "東根市立長瀞小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "13",
		"url" => "chubu-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "13",
		"school"=> "東根市立東根中部小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "14",
		"url" => "ohmori-higashine.edumap.jp",
		"organization_id" => "2",
		"organization"=> "東根市教育委員会",
		"school_id"=> "14",
		"school"=> "東根市立大森小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062111",
		"city"=> "東根市",
		"type"=> "小学校"
	),
	array(
		"id" => "15",
		"url" => "shibahinotsume.edumap.jp",
		"organization_id" => "4",
		"organization"=> "川口市立芝樋ノ爪小学校",
		"school_id"=> "21",
		"school"=> "川口市立芝樋ノ爪小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "16",
		"url" => "fermata-tsurumine-nursery-school.edumap.jp",
		"organization_id" => "5",
		"organization"=> "社会福祉法人愛和",
		"school_id"=> "308",
		"school"=> "鶴嶺フェルマータ保育園",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "142077",
		"city"=> "茅ヶ崎市",
		"type"=> "保育園"
	),
	array(
		"id" => "17",
		"url" => "fermata-tsumada-s-nursery.edumap.jp",
		"organization_id" => "5",
		"organization"=> "社会福祉法人愛和",
		"school_id"=> "20",
		"school"=> "妻田フェルマータ小規模保育園",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "142123",
		"city"=> "厚木市",
		"type"=> "保育園"
	),
	array(
		"id" => "18",
		"url" => "fermata-sekiguchi-s-nursery.edumap.jp",
		"organization_id" => "5",
		"organization"=> "社会福祉法人愛和",
		"school_id"=> "44",
		"school"=> "関口フェルマータ小規模保育園",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "142123",
		"city"=> "厚木市",
		"type"=> "保育園"
	),
	array(
		"id" => "19",
		"url" => "kujira-tekurada-hoikuen-natori-m.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "117",
		"school"=> "手倉田くじら保育園",
		"prefecture_id"=> "04",
		"prefecture"=> "宮城県",
		"city_id"=> "042072",
		"city"=> "名取市",
		"type"=> "保育園"
	),
	array(
		"id" => "20",
		"url" => "kujira-baobabu-hoikuen-osaki-mg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "116",
		"school"=> "バオバブ保育園",
		"prefecture_id"=> "04",
		"prefecture"=> "宮城県",
		"city_id"=> "042153",
		"city"=> "大崎市",
		"type"=> "保育園"
	),
	array(
		"id" => "21",
		"url" => "kujira-omusubi-kodomoen-niigata.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "95",
		"school"=> "おむすびこども園",
		"prefecture_id"=> "15",
		"prefecture"=> "新潟県",
		"city_id"=> "151025",
		"city"=> "新潟市東区",
		"type"=> "認定こども園"
	),
	array(
		"id" => "22",
		"url" => "kujira-suika-hoikuen-niigata.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "93",
		"school"=> "すいか保育園",
		"prefecture_id"=> "15",
		"prefecture"=> "新潟県",
		"city_id"=> "151076",
		"city"=> "新潟市西区",
		"type"=> "保育園"
	),
	array(
		"id" => "23",
		"url" => "kujira-suika-s-hoikuen-niigata.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "94",
		"school"=> "すいか小規模保育園",
		"prefecture_id"=> "15",
		"prefecture"=> "新潟県",
		"city_id"=> "151076",
		"city"=> "新潟市西区",
		"type"=> "保育園"
	),
	array(
		"id" => "24",
		"url" => "kujira-ishiyama-hoikuen-otsu-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "106",
		"school"=> "石山くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252018",
		"city"=> "大津市",
		"type"=> "保育園"
	),
	array(
		"id" => "25",
		"url" => "kujira-ishiyama-s-hoikuen-ots-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "107",
		"school"=> "石山くじら小規模保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252018",
		"city"=> "大津市",
		"type"=> "保育園"
	),
	array(
		"id" => "26",
		"url" => "kujira-katata-hoikuen-otsu-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "108",
		"school"=> "堅田くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252018",
		"city"=> "大津市",
		"type"=> "保育園"
	),
	array(
		"id" => "27",
		"url" => "kujira-karahashi-s-hoikuen-ots.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "110",
		"school"=> "唐橋くじら小規模保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252018",
		"city"=> "大津市",
		"type"=> "保育園"
	),
	array(
		"id" => "28",
		"url" => "kujira-biwako-hoikuen-kusatsu-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "111",
		"school"=> "琵琶湖くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252069",
		"city"=> "草津市",
		"type"=> "保育園"
	),
	array(
		"id" => "29",
		"url" => "kujira-kusatsu-hoikuen-kusats-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "112",
		"school"=> "くじら小規模保育園(草津)",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252069",
		"city"=> "草津市",
		"type"=> "保育園"
	),
	array(
		"id" => "30",
		"url" => "kujira-kusatsu-cho-hoikuen-kusatsu-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "323",
		"school"=> "(仮称)草津くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252069",
		"city"=> "草津市",
		"type"=> "保育園"
	),
	array(
		"id" => "31",
		"url" => "kujira-oiwake-minami-hoikuen-kusatsu-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "324",
		"school"=> "(仮称)追分南くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252069",
		"city"=> "草津市",
		"type"=> "保育園"
	),
	array(
		"id" => "32",
		"url" => "kujira-jidoclub-kusatsu-shiga.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "121",
		"school"=> "児童育成クラブくじら(草津)",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252069",
		"city"=> "草津市",
		"type"=> "小学校"
	),
	array(
		"id" => "33",
		"url" => "kujira-haruta-gakudou-ritto-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "91",
		"school"=> "治田くじら学童保育所",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252085",
		"city"=> "栗東市",
		"type"=> "保育園"
	),
	array(
		"id" => "34",
		"url" => "kujira-haruta-e-gakudo-ritto-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "92",
		"school"=> "治田東くじら学童保育所",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252085",
		"city"=> "栗東市",
		"type"=> "保育園"
	),
	array(
		"id" => "35",
		"url" => "kujira-ritto-hoikuen-ritto-shiga.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "113",
		"school"=> "栗東くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252085",
		"city"=> "栗東市",
		"type"=> "保育園"
	),
	array(
		"id" => "36",
		"url" => "kujira-ritto-s-hoikuen-ritto-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "114",
		"school"=> "栗東くじら小規模保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252085",
		"city"=> "栗東市",
		"type"=> "保育園"
	),
	array(
		"id" => "37",
		"url" => "kujira-haruta-s-hoikuen-ritto-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "115",
		"school"=> "治田くじら小規模保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252085",
		"city"=> "栗東市",
		"type"=> "保育園"
	),
	array(
		"id" => "38",
		"url" => "kujira-mikumo-hoikuen-konan-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "88",
		"school"=> "三雲くじら保育園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252115",
		"city"=> "湖南市",
		"type"=> "保育園"
	),
	array(
		"id" => "39",
		"url" => "kujira-bodaiji-kodomoen-konan-sg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "89",
		"school"=> "菩提寺くじらこども園",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252115",
		"city"=> "湖南市",
		"type"=> "認定こども園"
	),
	array(
		"id" => "40",
		"url" => "kujira-senriyama-hoikuen-suita.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "105",
		"school"=> "千里山くじら保育園",
		"prefecture_id"=> "27",
		"prefecture"=> "大阪府",
		"city_id"=> "272051",
		"city"=> "吹田市",
		"type"=> "保育園"
	),
	array(
		"id" => "41",
		"url" => "kujira-uenomaru-hoikuen-akashi-hyogo.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "316",
		"school"=> "（仮称）上ノ丸くじら保育園",
		"prefecture_id"=> "28",
		"prefecture"=> "兵庫県",
		"city_id"=> "282031",
		"city"=> "明石市",
		"type"=> "保育園"
	),
	array(
		"id" => "42",
		"url" => "kujira-umenoki-hoikuen-itami-hg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "90",
		"school"=> "梅ノ木くじら保育園",
		"prefecture_id"=> "28",
		"prefecture"=> "兵庫県",
		"city_id"=> "282073",
		"city"=> "伊丹市",
		"type"=> "保育園"
	),
	array(
		"id" => "43",
		"url" => "kujira-itam-hoikuen-itami-hyogo.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "103",
		"school"=> "伊丹くじら保育園",
		"prefecture_id"=> "28",
		"prefecture"=> "兵庫県",
		"city_id"=> "282073",
		"city"=> "伊丹市",
		"type"=> "保育園"
	),
	array(
		"id" => "44",
		"url" => "kujira-itam-s-hoikuen-itami-hyg.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "104",
		"school"=> "伊丹くじら小規模保育園",
		"prefecture_id"=> "28",
		"prefecture"=> "兵庫県",
		"city_id"=> "282073",
		"city"=> "伊丹市",
		"type"=> "保育園"
	),
	array(
		"id" => "45",
		"url" => "kujira-koushi-hatsukaichi-hirosm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "86",
		"school"=> "廿日市保育園 (公私連携型保育所)",
		"prefecture_id"=> "34",
		"prefecture"=> "広島県",
		"city_id"=> "342131",
		"city"=> "廿日市市",
		"type"=> "保育園"
	),
	array(
		"id" => "46",
		"url" => "kujira-hatsukaichi-hoikuen-hirsm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "102",
		"school"=> "廿日市くじら保育園",
		"prefecture_id"=> "34",
		"prefecture"=> "広島県",
		"city_id"=> "342131",
		"city"=> "廿日市市",
		"type"=> "保育園"
	),
	array(
		"id" => "47",
		"url" => "kujira-torinoki-hoikuen-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "87",
		"school"=> "とりのきくじら保育園",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "保育園"
	),
	array(
		"id" => "48",
		"url" => "kujira-penguin-s-hoikuen-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "98",
		"school"=> "伊予ぺんぎん小規模保育園",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "保育園"
	),
	array(
		"id" => "49",
		"url" => "kujira-manbou-s-hoikuen-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "99",
		"school"=> "まんぼう小規模保育園",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "保育園"
	),
	array(
		"id" => "50",
		"url" => "kujira-dayservice-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "100",
		"school"=> "放課後等デイサービスくじら",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "小中一貫校・義務教育学校"
	),
	array(
		"id" => "51",
		"url" => "kujira-iyo-jido-club-iyo-ehime.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "122",
		"school"=> "伊予くじら児童クラブ",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "小学校"
	),
	array(
		"id" => "52",
		"url" => "kujira-iyo-group-home-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "313",
		"school"=> "グループホーム伊予くじら",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "特別支援学校"
	),
	array(
		"id" => "53",
		"url" => "kujira-iyo-jido-hattatsu-shien-center.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "314",
		"school"=> "児童発達支援センター伊予くじら",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "特別支援学校"
	),
	array(
		"id" => "54",
		"url" => "kujira-iyo-kodomoen-iyo-ehm.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "97",
		"school"=> "伊予くじら認定こども園",
		"prefecture_id"=> "38",
		"prefecture"=> "愛媛県",
		"city_id"=> "382108",
		"city"=> "伊予市",
		"type"=> "認定こども園"
	),
	array(
		"id" => "55",
		"url" => "kujira-jido-shinri-chiryo-fuku.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "123",
		"school"=> "福岡市立児童心理治療施設",
		"prefecture_id"=> "40",
		"prefecture"=> "福岡県",
		"city_id"=> "401331",
		"city"=> "福岡市中央区",
		"type"=> "特別支援学校"
	),
	array(
		"id" => "56",
		"url" => "kujira-kodomoen-omura-nagasaki.edumap.jp",
		"organization_id" => "6",
		"organization"=> "社会福祉法人くじら",
		"school_id"=> "63",
		"school"=> "くじら認定こども園",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "422053",
		"city"=> "大村市",
		"type"=> "認定こども園"
	),
	array(
		"id" => "57",
		"url" => "honcho-e-kawaguchi.edumap.jp",
		"organization_id" => "7",
		"organization"=> "埼玉県川口市立本町小学校",
		"school_id"=> "29",
		"school"=> "埼玉県川口市立本町小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "58",
		"url" => "takanosu-e.edumap.jp",
		"organization_id" => "8",
		"organization"=> "砺波市立鷹栖小学校",
		"school_id"=> "27",
		"school"=> "砺波市立鷹栖小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "162086",
		"city"=> "砺波市",
		"type"=> "小学校"
	),
	array(
		"id" => "59",
		"url" => "kita.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "33",
		"school"=> "伊東市立北中学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "中学校"
	),
	array(
		"id" => "60",
		"url" => "minami-jh.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "34",
		"school"=> "伊東市立南中学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "中学校"
	),
	array(
		"id" => "61",
		"url" => "usami-jh.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "49",
		"school"=> "伊東市立宇佐美中学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "中学校"
	),
	array(
		"id" => "62",
		"url" => "tajima.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "50",
		"school"=> "伊東市立対島中学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "中学校"
	),
	array(
		"id" => "63",
		"url" => "kadono.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "51",
		"school"=> "伊東市立門野中学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "中学校"
	),
	array(
		"id" => "64",
		"url" => "futo.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "22",
		"school"=> "伊東市立富戸小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "65",
		"url" => "kawana.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "24",
		"school"=> "伊東市立川奈小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "66",
		"url" => "ike.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "25",
		"school"=> "伊東市立池小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "67",
		"url" => "yawatano.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "26",
		"school"=> "伊東市立八幡野小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "68",
		"url" => "higashi.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "31",
		"school"=> "伊東市立東小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "69",
		"url" => "nishi.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "32",
		"school"=> "伊東市立西小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "70",
		"url" => "minami.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "35",
		"school"=> "伊東市立南小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "71",
		"url" => "ooike.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "46",
		"school"=> "伊東市立大池小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "72",
		"url" => "usami.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "47",
		"school"=> "伊東市立宇佐美小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "73",
		"url" => "asahi.edumap.jp",
		"organization_id" => "9",
		"organization"=> "伊東市教育委員会",
		"school_id"=> "48",
		"school"=> "伊東市立旭小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222089",
		"city"=> "伊東市",
		"type"=> "小学校"
	),
	array(
		"id" => "74",
		"url" => "serita-tobu.edumap.jp",
		"organization_id" => "10",
		"organization"=> "芹田東部保育園",
		"school_id"=> "23",
		"school"=> "芹田東部保育園",
		"prefecture_id"=> "20",
		"prefecture"=> "長野県",
		"city_id"=> "202011",
		"city"=> "長野市",
		"type"=> "保育園"
	),
	array(
		"id" => "75",
		"url" => "maesawa-jhs-oshu-iwate.edumap.jp",
		"organization_id" => "12",
		"organization"=> "奥州市立前沢中学校",
		"school_id"=> "45",
		"school"=> "奥州市立前沢中学校",
		"prefecture_id"=> "03",
		"prefecture"=> "岩手県",
		"city_id"=> "032158",
		"city"=> "奥州市",
		"type"=> "中学校"
	),
	array(
		"id" => "76",
		"url" => "todukasyou1.edumap.jp",
		"organization_id" => "13",
		"organization"=> "川口市立戸塚小学校",
		"school_id"=> "144",
		"school"=> "川口市立戸塚小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "77",
		"url" => "daito-web.edumap.jp",
		"organization_id" => "14",
		"organization"=> "福井市大東中学校",
		"school_id"=> "30",
		"school"=> "福井市大東中学校",
		"prefecture_id"=> "18",
		"prefecture"=> "福井県",
		"city_id"=> "182010",
		"city"=> "福井市",
		"type"=> "中学校"
	),
	array(
		"id" => "78",
		"url" => "kawaguchisiritukitat-saitama.edumap.jp",
		"organization_id" => "15",
		"organization"=> "川口市立北中学校",
		"school_id"=> "62",
		"school"=> "川口市立北中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "79",
		"url" => "asahinishi-e.edumap.jp",
		"organization_id" => "16",
		"organization"=> "川口市立朝日西小学校",
		"school_id"=> "166",
		"school"=> "川口市立朝日西小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "80",
		"url" => "kahoku-jh-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "43",
		"school"=> "河北中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "中学校"
	),
	array(
		"id" => "81",
		"url" => "nishizato-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "37",
		"school"=> "西里小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "82",
		"url" => "mizonobe-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "38",
		"school"=> "溝延小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "83",
		"url" => "yachichubu-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "39",
		"school"=> "谷地中部小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "84",
		"url" => "yachinanbu-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "40",
		"school"=> "谷地南部小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "85",
		"url" => "yachiseibu-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "41",
		"school"=> "谷地西部小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "86",
		"url" => "kitayachi-kahoku.edumap.jp",
		"organization_id" => "18",
		"organization"=> "河北町教育委員会",
		"school_id"=> "42",
		"school"=> "北谷地小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "063215",
		"city"=> "河北町",
		"type"=> "小学校"
	),
	array(
		"id" => "87",
		"url" => "sch-kawaguchi-sakuracho.edumap.jp",
		"organization_id" => "19",
		"organization"=> "川口市立桜町小学校",
		"school_id"=> "52",
		"school"=> "川口市立桜町小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "88",
		"url" => "iruka-hoikuen-nagasaki.edumap.jp",
		"organization_id" => "20",
		"organization"=> "小規模保育園いるか",
		"school_id"=> "36",
		"school"=> "小規模保育園いるか",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "422053",
		"city"=> "大村市",
		"type"=> "保育園"
	),
	array(
		"id" => "89",
		"url" => "oyama-j.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "71",
		"school"=> "雄山中学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "中学校"
	),
	array(
		"id" => "90",
		"url" => "tateyamahokubu-e.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "65",
		"school"=> "立山北部小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "91",
		"url" => "rita-el-school.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "66",
		"school"=> "利田小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "92",
		"url" => "takano-e.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "67",
		"school"=> "高野小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "93",
		"url" => "tateyama-chuo-e.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "68",
		"school"=> "立山中央小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "94",
		"url" => "kamagafuchi-e.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "69",
		"school"=> "釜ヶ渕小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "95",
		"url" => "tateyama-e.edumap.jp",
		"organization_id" => "21",
		"organization"=> "立山町教育委員会",
		"school_id"=> "70",
		"school"=> "立山小学校",
		"prefecture_id"=> "16",
		"prefecture"=> "富山県",
		"city_id"=> "163236",
		"city"=> "立山町",
		"type"=> "小学校"
	),
	array(
		"id" => "96",
		"url" => "ninomiya-junior-high-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "58",
		"school"=> "二宮町立二宮中学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "中学校"
	),
	array(
		"id" => "97",
		"url" => "ninomiyanishi-junior-high-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "59",
		"school"=> "二宮町立二宮西中学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "中学校"
	),
	array(
		"id" => "98",
		"url" => "ninomiya-elementary-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "55",
		"school"=> "二宮町立二宮小学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "小学校"
	),
	array(
		"id" => "99",
		"url" => "issiki-elementry-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "56",
		"school"=> "二宮町立一色小学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "小学校"
	),
	array(
		"id" => "100",
		"url" => "yamanishi-erementary-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "57",
		"school"=> "二宮町立山西小学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "小学校"
	),
	array(
		"id" => "101",
		"url" => "isshiki-elementary-school.edumap.jp",
		"organization_id" => "22",
		"organization"=> "二宮町教育委員会",
		"school_id"=> "228",
		"school"=> "二宮町立一色小学校",
		"prefecture_id"=> "14",
		"prefecture"=> "神奈川県",
		"city_id"=> "143421",
		"city"=> "二宮町",
		"type"=> "小学校"
	),
	array(
		"id" => "102",
		"url" => "misatojh.edumap.jp",
		"organization_id" => "24",
		"organization"=> "美里町立美里中学校",
		"school_id"=> "73",
		"school"=> "美里町立美里中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "113816",
		"city"=> "美里町",
		"type"=> "中学校"
	),
	array(
		"id" => "103",
		"url" => "daiichi-j-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "72",
		"school"=> "蕨市立第一中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "中学校"
	),
	array(
		"id" => "104",
		"url" => "higashi-j-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "318",
		"school"=> "蕨市立東中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "中学校"
	),
	array(
		"id" => "105",
		"url" => "tsukagoshi-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "75",
		"school"=> "蕨市立塚越小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "106",
		"url" => "chuo-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "76",
		"school"=> "蕨市立中央小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "107",
		"url" => "nishi-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "85",
		"school"=> "蕨市立西小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "108",
		"url" => "chuohigashi-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "119",
		"school"=> "蕨市立中央東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "109",
		"url" => "higashi-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "160",
		"school"=> "蕨市立東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "110",
		"url" => "minami-e-warabi.edumap.jp",
		"organization_id" => "25",
		"organization"=> "蕨市教育委員会",
		"school_id"=> "230",
		"school"=> "蕨市立南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "111",
		"url" => "kawaguchi-municipal-aokikita-ele.edumap.jp",
		"organization_id" => "26",
		"organization"=> "川口市立青木北小学校",
		"school_id"=> "54",
		"school"=> "川口市立青木北小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "112",
		"url" => "niimi-city-niimiminami-elementar.edumap.jp",
		"organization_id" => "27",
		"organization"=> "新見市立新見南小学校",
		"school_id"=> "82",
		"school"=> "新見市立新見南小学校",
		"prefecture_id"=> "33",
		"prefecture"=> "岡山県",
		"city_id"=> "332101",
		"city"=> "新見市",
		"type"=> "小学校"
	),
	array(
		"id" => "113",
		"url" => "furano-nishi-jhs.edumap.jp",
		"organization_id" => "28",
		"organization"=> "富良野市立富良野西中学校",
		"school_id"=> "64",
		"school"=> "富良野市立富良野西中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012297",
		"city"=> "富良野市",
		"type"=> "中学校"
	),
	array(
		"id" => "114",
		"url" => "motogo-elementary-school.edumap.jp",
		"organization_id" => "29",
		"organization"=> "川口市立元郷小学校",
		"school_id"=> "74",
		"school"=> "川口市立元郷小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "115",
		"url" => "nasuchuo-jh.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "81",
		"school"=> "那須中央中中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "中学校"
	),
	array(
		"id" => "116",
		"url" => "nasu-jh.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "138",
		"school"=> "那須中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "中学校"
	),
	array(
		"id" => "117",
		"url" => "nasukougen.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "79",
		"school"=> "那須高原小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "118",
		"url" => "tashiroyuuai.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "80",
		"school"=> "田代友愛小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "119",
		"url" => "kurodahara.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "109",
		"school"=> "黒田原小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "120",
		"url" => "toyo.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "139",
		"school"=> "東陽小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "121",
		"url" => "takaku.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "142",
		"school"=> "高久小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "122",
		"url" => "manabinomori.edumap.jp",
		"organization_id" => "31",
		"organization"=> "那須町教育委員会",
		"school_id"=> "146",
		"school"=> "学びの森小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "094072",
		"city"=> "那須町",
		"type"=> "小学校"
	),
	array(
		"id" => "123",
		"url" => "shibaminami.edumap.jp",
		"organization_id" => "33",
		"organization"=> "川口市立芝南小学校",
		"school_id"=> "131",
		"school"=> "川口市立芝南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "124",
		"url" => "tendo2jh.edumap.jp",
		"organization_id" => "34",
		"organization"=> "天童市立第二中学校",
		"school_id"=> "96",
		"school"=> "天童市立第二中学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062103",
		"city"=> "天童市",
		"type"=> "中学校"
	),
	array(
		"id" => "125",
		"url" => "hatogaya.edumap.jp",
		"organization_id" => "35",
		"organization"=> "川口市立鳩ヶ谷小学校",
		"school_id"=> "101",
		"school"=> "川口市立鳩ヶ谷小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "126",
		"url" => "tokorozawa-city-seisin-e-saitama.edumap.jp",
		"organization_id" => "37",
		"organization"=> "埼玉県所沢市立清進小学校",
		"school_id"=> "132",
		"school"=> "埼玉県所沢市立清進小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "小学校"
	),
	array(
		"id" => "127",
		"url" => "c-niiza.edumap.jp",
		"organization_id" => "38",
		"organization"=> "新座市立第三中学校",
		"school_id"=> "120",
		"school"=> "新座市立第三中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112305",
		"city"=> "新座市",
		"type"=> "中学校"
	),
	array(
		"id" => "128",
		"url" => "www-sch-todukakita-kawaguchi.edumap.jp",
		"organization_id" => "40",
		"organization"=> "川口市立戸塚北小学校",
		"school_id"=> "126",
		"school"=> "川口市立戸塚北小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "129",
		"url" => "ibukiyama-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "124",
		"school"=> "米原市立伊吹山中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "130",
		"url" => "kashiwabara-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "125",
		"school"=> "米原市立柏原中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "131",
		"url" => "souyou-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "129",
		"school"=> "米原市立双葉中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "132",
		"url" => "kanan-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "147",
		"school"=> "米原市立河南中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "133",
		"url" => "daito-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "238",
		"school"=> "米原市立大東中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "134",
		"url" => "maibara-j-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "322",
		"school"=> "米原市立米原中学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "中学校"
	),
	array(
		"id" => "135",
		"url" => "kashiwabara-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "127",
		"school"=> "米原市立柏原小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "136",
		"url" => "suijyou-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "130",
		"school"=> "米原市立春照小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "137",
		"url" => "maibara-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "137",
		"school"=> "米原市立米原小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "138",
		"url" => "santo-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "140",
		"school"=> "米原市立山東小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "139",
		"url" => "kanan-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "258",
		"school"=> "米原市立河南小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "140",
		"url" => "ibuki-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "259",
		"school"=> "米原市立伊吹小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "141",
		"url" => "ohara-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "319",
		"school"=> "米原市立大原小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "142",
		"url" => "okinaga-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "320",
		"school"=> "米原市立息長小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "143",
		"url" => "sakata-e-maibara.edumap.jp",
		"organization_id" => "41",
		"organization"=> "米原市教育委員会",
		"school_id"=> "321",
		"school"=> "米原市立坂田小学校",
		"prefecture_id"=> "25",
		"prefecture"=> "滋賀県",
		"city_id"=> "252140",
		"city"=> "米原市",
		"type"=> "小学校"
	),
	array(
		"id" => "144",
		"url" => "togitsu-higashi.edumap.jp",
		"organization_id" => "42",
		"organization"=> "時津町立時津東小学校",
		"school_id"=> "141",
		"school"=> "時津町立時津東小学校",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "423084",
		"city"=> "時津町",
		"type"=> "小学校"
	),
	array(
		"id" => "145",
		"url" => "kitamifuji.edumap.jp",
		"organization_id" => "43",
		"organization"=> "北見藤高等学校",
		"school_id"=> "134",
		"school"=> "北見藤高等学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012084",
		"city"=> "北見市",
		"type"=> "高等学校"
	),
	array(
		"id" => "146",
		"url" => "haramachi-kawaguchi.edumap.jp",
		"organization_id" => "44",
		"organization"=> "埼玉県川口市立原町小学校",
		"school_id"=> "128",
		"school"=> "川口原町小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "147",
		"url" => "kisochouritu-fukushimashougakkou.edumap.jp",
		"organization_id" => "45",
		"organization"=> "木曽町立福島小学校",
		"school_id"=> "143",
		"school"=> "木曽町立福島小学校",
		"prefecture_id"=> "20",
		"prefecture"=> "長野県",
		"city_id"=> "204323",
		"city"=> "木曽町",
		"type"=> "小学校"
	),
	array(
		"id" => "148",
		"url" => "kawaguchi-jirin-e.edumap.jp",
		"organization_id" => "46",
		"organization"=> "川口市立慈林小学校",
		"school_id"=> "133",
		"school"=> "川口市立慈林小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "149",
		"url" => "roppongi-high-school.edumap.jp",
		"organization_id" => "47",
		"organization"=> "東京都立六本木高等学校",
		"school_id"=> "136",
		"school"=> "東京都立六本木高等学校",
		"prefecture_id"=> "13",
		"prefecture"=> "東京都",
		"city_id"=> "131032",
		"city"=> "港区",
		"type"=> "高等学校"
	),
	array(
		"id" => "150",
		"url" => "sch-kawaguchi-saitama.edumap.jp",
		"organization_id" => "48",
		"organization"=> "川口市立根岸小学校",
		"school_id"=> "153",
		"school"=> "川口市立根岸小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "151",
		"url" => "shikige-jh.edumap.jp",
		"organization_id" => "49",
		"organization"=> "川西町・三宅町式下中学校組合教育委員会",
		"school_id"=> "145",
		"school"=> "式下中学校",
		"prefecture_id"=> "29",
		"prefecture"=> "奈良県",
		"city_id"=> "293610",
		"city"=> "川西町",
		"type"=> "中学校"
	),
	array(
		"id" => "152",
		"url" => "kouyou-jh-tokorozawa-stm.edumap.jp",
		"organization_id" => "51",
		"organization"=> "所沢市立向陽中学校",
		"school_id"=> "158",
		"school"=> "所沢市立向陽中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "中学校"
	),
	array(
		"id" => "153",
		"url" => "kawaguchi-shiba-jh.edumap.jp",
		"organization_id" => "52",
		"organization"=> "川口市立芝中学校",
		"school_id"=> "149",
		"school"=> "川口市立芝中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "154",
		"url" => "kita-e-warabi.edumap.jp",
		"organization_id" => "54",
		"organization"=> "蕨市立北小学校",
		"school_id"=> "155",
		"school"=> "蕨市立北小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112232",
		"city"=> "蕨市",
		"type"=> "小学校"
	),
	array(
		"id" => "155",
		"url" => "tokorozawa-city-kitano-e-saitama.edumap.jp",
		"organization_id" => "55",
		"organization"=> "所沢市立北野小学校",
		"school_id"=> "163",
		"school"=> "所沢市立北野小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "小学校"
	),
	array(
		"id" => "156",
		"url" => "hakodatekita.edumap.jp",
		"organization_id" => "56",
		"organization"=> "函館市立北中学校",
		"school_id"=> "157",
		"school"=> "函館市立北中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012025",
		"city"=> "函館市",
		"type"=> "中学校"
	),
	array(
		"id" => "157",
		"url" => "tozukahigashi-e-kawaguchi.edumap.jp",
		"organization_id" => "58",
		"organization"=> "川口市立戸塚東小学校",
		"school_id"=> "156",
		"school"=> "川口市立戸塚東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "158",
		"url" => "atami-dai1.edumap.jp",
		"organization_id" => "59",
		"organization"=> "熱海市立第一小学校",
		"school_id"=> "159",
		"school"=> "熱海市立第一小学校",
		"prefecture_id"=> "22",
		"prefecture"=> "静岡県",
		"city_id"=> "222054",
		"city"=> "熱海市",
		"type"=> "小学校"
	),
	array(
		"id" => "159",
		"url" => "mito-jh.edumap.jp",
		"organization_id" => "61",
		"organization"=> "益田市立美都中学校",
		"school_id"=> "161",
		"school"=> "益田市立美都中学校",
		"prefecture_id"=> "32",
		"prefecture"=> "島根県",
		"city_id"=> "322041",
		"city"=> "益田市",
		"type"=> "中学校"
	),
	array(
		"id" => "160",
		"url" => "tutu-elementary-school.edumap.jp",
		"organization_id" => "62",
		"organization"=> "対馬市立豆酘小学校",
		"school_id"=> "162",
		"school"=> "対馬市立豆酘小学校",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "422096",
		"city"=> "対馬市",
		"type"=> "小学校"
	),
	array(
		"id" => "161",
		"url" => "sachinami09.edumap.jp",
		"organization_id" => "63",
		"organization"=> "川口市立幸並中学校",
		"school_id"=> "270",
		"school"=> "川口市立幸並中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "162",
		"url" => "togitsu-elementa-nagasaki.edumap.jp",
		"organization_id" => "64",
		"organization"=> "時津町立時津小学校",
		"school_id"=> "164",
		"school"=> "時津町立時津小学校",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "423084",
		"city"=> "時津町",
		"type"=> "小学校"
	),
	array(
		"id" => "163",
		"url" => "sch-kawaguchi-singominami.edumap.jp",
		"organization_id" => "66",
		"organization"=> "川口市立新郷南小学校",
		"school_id"=> "165",
		"school"=> "川口市立新郷南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "164",
		"url" => "kitatama-e.edumap.jp",
		"organization_id" => "68",
		"organization"=> "北谷町教育委員会",
		"school_id"=> "315",
		"school"=> "北谷町立　北玉小学校",
		"prefecture_id"=> "47",
		"prefecture"=> "沖縄県",
		"city_id"=> "473260",
		"city"=> "北谷町",
		"type"=> "小学校"
	),
	array(
		"id" => "165",
		"url" => "konosu-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "186",
		"school"=> "鴻巣市立鴻巣中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "166",
		"url" => "kokita-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "187",
		"school"=> "鴻巣市立鴻巣北中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "167",
		"url" => "konishi-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "188",
		"school"=> "鴻巣市立鴻巣西中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "168",
		"url" => "kominami-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "189",
		"school"=> "鴻巣市立鴻巣南中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "169",
		"url" => "akamidai-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "190",
		"school"=> "鴻巣市立赤見台中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "170",
		"url" => "fukiage-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "191",
		"school"=> "鴻巣市立吹上中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "171",
		"url" => "fukiagekita-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "192",
		"school"=> "鴻巣市立吹上北中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "172",
		"url" => "kawasato-j-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "193",
		"school"=> "鴻巣市立川里中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "中学校"
	),
	array(
		"id" => "173",
		"url" => "matubara-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "167",
		"school"=> "鴻巣市立松原小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "174",
		"url" => "aka1-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "168",
		"school"=> "鴻巣市立赤見台第一小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "175",
		"url" => "aka2-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "169",
		"school"=> "鴻巣市立赤見台第二小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "176",
		"url" => "kochuo-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "170",
		"school"=> "鴻巣市立鴻巣中央小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "177",
		"url" => "kyowa-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "171",
		"school"=> "鴻巣市立共和小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "178",
		"url" => "kohigashi-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "172",
		"school"=> "鴻巣市立鴻巣東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "179",
		"url" => "kominami-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "173",
		"school"=> "鴻巣市立鴻巣南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "180",
		"url" => "mamuro-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "174",
		"school"=> "鴻巣市立馬室小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "181",
		"url" => "tamamiya-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "175",
		"school"=> "鴻巣市立田間宮小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "182",
		"url" => "mida-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "176",
		"school"=> "鴻巣市立箕田小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "183",
		"url" => "kasahara-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "177",
		"school"=> "鴻巣市立笠原小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "184",
		"url" => "jyoko-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "178",
		"school"=> "鴻巣市立常光小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "185",
		"url" => "kokita-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "179",
		"school"=> "鴻巣市立鴻巣北小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "186",
		"url" => "fukiage-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "180",
		"school"=> "鴻巣市立吹上小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "187",
		"url" => "koya-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "181",
		"school"=> "鴻巣市立小谷小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "188",
		"url" => "shimooshi-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "182",
		"school"=> "鴻巣市立下忍小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "189",
		"url" => "oashi-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "183",
		"school"=> "鴻巣市立大芦小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "190",
		"url" => "kusu-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "184",
		"school"=> "鴻巣市立屈巣小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "191",
		"url" => "hiroda-e-konosu.edumap.jp",
		"organization_id" => "69",
		"organization"=> "鴻巣市教育委員会",
		"school_id"=> "185",
		"school"=> "鴻巣市立広田小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112178",
		"city"=> "鴻巣市",
		"type"=> "小学校"
	),
	array(
		"id" => "192",
		"url" => "higashiryoke-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "70",
		"organization"=> "川口市立東領家小学校",
		"school_id"=> "194",
		"school"=> "川口市立東領家小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "193",
		"url" => "tozukaayase-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "71",
		"organization"=> "川口市立戸塚綾瀬小学校",
		"school_id"=> "195",
		"school"=> "川口市立戸塚綾瀬小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "194",
		"url" => "kamiaokiminami-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "72",
		"organization"=> "川口市立上青木南小学校",
		"school_id"=> "196",
		"school"=> "川口市立上青木南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "195",
		"url" => "ryoke-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "73",
		"organization"=> "川口市立領家小学校",
		"school_id"=> "197",
		"school"=> "川口市立領家小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "196",
		"url" => "tozukaminami-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "74",
		"organization"=> "川口市立戸塚南小学校",
		"school_id"=> "198",
		"school"=> "川口市立戸塚南小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "197",
		"url" => "kamiaoki-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "75",
		"organization"=> "川口市立上青木小学校",
		"school_id"=> "199",
		"school"=> "川口市立上青木小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "198",
		"url" => "zaike-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "76",
		"organization"=> "川口市立在家中学校",
		"school_id"=> "200",
		"school"=> "川口市立在家中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "199",
		"url" => "yanagisaki-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "77",
		"organization"=> "川口市立柳崎小学校",
		"school_id"=> "201",
		"school"=> "川口市立柳崎小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "200",
		"url" => "maekawahigashi-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "78",
		"organization"=> "川口市立前川東小学校",
		"school_id"=> "202",
		"school"=> "川口市立前川東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "201",
		"url" => "nanpei-k-kawaguchi-saitama.edumap.jp",
		"organization_id" => "79",
		"organization"=> "川口市立南平幼稚園",
		"school_id"=> "203",
		"school"=> "川口市立南平幼稚園",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "幼稚園"
	),
	array(
		"id" => "202",
		"url" => "kamine-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "80",
		"organization"=> "川口市立神根中学校",
		"school_id"=> "204",
		"school"=> "川口市立神根中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "203",
		"url" => "haimatu-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "81",
		"organization"=> "川口市立榛松中学校",
		"school_id"=> "205",
		"school"=> "川口市立榛松中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "204",
		"url" => "tozuka-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "82",
		"organization"=> "川口市立戸塚中学校",
		"school_id"=> "206",
		"school"=> "川口市立戸塚中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "205",
		"url" => "aoki-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "83",
		"organization"=> "川口市立青木中学校",
		"school_id"=> "207",
		"school"=> "川口市立青木中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "206",
		"url" => "shibanishi-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "84",
		"organization"=> "川口市立芝西中学校",
		"school_id"=> "208",
		"school"=> "川口市立芝西中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "207",
		"url" => "zaike-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "85",
		"organization"=> "川口市立在家小学校",
		"school_id"=> "209",
		"school"=> "川口市立在家小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "208",
		"url" => "motogo-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "86",
		"organization"=> "川口市立元郷中学校",
		"school_id"=> "210",
		"school"=> "川口市立元郷中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "209",
		"url" => "tozukanishi-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "87",
		"organization"=> "川口市立戸塚西中学校",
		"school_id"=> "211",
		"school"=> "川口市立戸塚西中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "210",
		"url" => "shibanishi-yousyun-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "88",
		"organization"=> "川口市立芝西中学校陽春分校",
		"school_id"=> "212",
		"school"=> "川口市立芝西中学校陽春分校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "211",
		"url" => "minami-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "89",
		"organization"=> "川口市立南中学校",
		"school_id"=> "213",
		"school"=> "川口市立南中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "212",
		"url" => "sashima-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "90",
		"organization"=> "川口市立差間小学校",
		"school_id"=> "214",
		"school"=> "川口市立差間小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "213",
		"url" => "shibafuji-es-kawaguchi-saitama.edumap.jp",
		"organization_id" => "91",
		"organization"=> "川口市立芝富士小学校",
		"school_id"=> "215",
		"school"=> "川口市立芝富士小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "214",
		"url" => "aokichuo-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "92",
		"organization"=> "川口市立青木中央小学校",
		"school_id"=> "216",
		"school"=> "川口市立青木中央小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "215",
		"url" => "minamihatogaya-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "93",
		"organization"=> "川口市立南鳩ヶ谷小学校",
		"school_id"=> "217",
		"school"=> "川口市立南鳩ヶ谷小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "216",
		"url" => "hunato-e-kawaguchi-saitama.edumap.jp",
		"organization_id" => "94",
		"organization"=> "川口市立舟戸小学校",
		"school_id"=> "218",
		"school"=> "川口市立舟戸小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "217",
		"url" => "kamiaoki-j-kawaguchi-saitama.edumap.jp",
		"organization_id" => "95",
		"organization"=> "川口市立上青木中学校",
		"school_id"=> "219",
		"school"=> "川口市立上青木中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "218",
		"url" => "funato-k-kawaguchi-saitama.edumap.jp",
		"organization_id" => "96",
		"organization"=> "川口市立舟戸幼稚園",
		"school_id"=> "220",
		"school"=> "川口市立舟戸幼稚園",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "幼稚園"
	),
	array(
		"id" => "219",
		"url" => "kawaguchicity-jh.edumap.jp",
		"organization_id" => "97",
		"organization"=> "川口市立高等学校附属中学校",
		"school_id"=> "221",
		"school"=> "川口市立高等学校附属中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "220",
		"url" => "kawaguchicity-hs.edumap.jp",
		"organization_id" => "97",
		"organization"=> "川口市立高等学校附属中学校",
		"school_id"=> "310",
		"school"=> "川口市立高等学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "高等学校"
	),
	array(
		"id" => "221",
		"url" => "nakatomi-eh-tokorozawa.edumap.jp",
		"organization_id" => "98",
		"organization"=> "所沢市立中富小学校",
		"school_id"=> "222",
		"school"=> "所沢市立中富小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "小学校"
	),
	array(
		"id" => "222",
		"url" => "mikajima-jh-tokorozawa.edumap.jp",
		"organization_id" => "99",
		"organization"=> "所沢市立三ヶ島中学校",
		"school_id"=> "223",
		"school"=> "所沢市立三ヶ島中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "中学校"
	),
	array(
		"id" => "223",
		"url" => "nakatyou.edumap.jp",
		"organization_id" => "101",
		"organization"=> "川口市立仲町中学校",
		"school_id"=> "227",
		"school"=> "川口市立仲町中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "中学校"
	),
	array(
		"id" => "224",
		"url" => "kamiizumi-elementary-school.edumap.jp",
		"organization_id" => "102",
		"organization"=> "神川町立神泉小学校",
		"school_id"=> "229",
		"school"=> "神川町立神泉小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "113832",
		"city"=> "神川町",
		"type"=> "小学校"
	),
	array(
		"id" => "225",
		"url" => "tonda-j-h-s-shirahama-town.edumap.jp",
		"organization_id" => "103",
		"organization"=> "白浜町立富田中学校",
		"school_id"=> "231",
		"school"=> "白浜町立富田中学校",
		"prefecture_id"=> "30",
		"prefecture"=> "和歌山県",
		"city_id"=> "304018",
		"city"=> "白浜町",
		"type"=> "中学校"
	),
	array(
		"id" => "226",
		"url" => "yanase-jh-tokorozawa-stm.edumap.jp",
		"organization_id" => "104",
		"organization"=> "所沢市立柳瀬中学校",
		"school_id"=> "232",
		"school"=> "所沢市立柳瀬中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "中学校"
	),
	array(
		"id" => "227",
		"url" => "nhatsu.edumap.jp",
		"organization_id" => "109",
		"organization"=> "流山市立西初石中学校",
		"school_id"=> "233",
		"school"=> "流山市立西初石中学校",
		"prefecture_id"=> "12",
		"prefecture"=> "千葉県",
		"city_id"=> "122203",
		"city"=> "流山市",
		"type"=> "中学校"
	),
	array(
		"id" => "228",
		"url" => "fukabori-jhs.edumap.jp",
		"organization_id" => "110",
		"organization"=> "函館市立深堀中学校",
		"school_id"=> "255",
		"school"=> "函館市立深堀中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012025",
		"city"=> "函館市",
		"type"=> "中学校"
	),
	array(
		"id" => "229",
		"url" => "hakodate-city-aoyagi-junior-high-school.edumap.jp",
		"organization_id" => "111",
		"organization"=> "函館市立青柳中学校",
		"school_id"=> "234",
		"school"=> "函館市立青柳中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012025",
		"city"=> "函館市",
		"type"=> "中学校"
	),
	array(
		"id" => "230",
		"url" => "asahioka-jh.edumap.jp",
		"organization_id" => "112",
		"organization"=> "函館市立旭岡中学校",
		"school_id"=> "237",
		"school"=> "函館市立旭岡中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012025",
		"city"=> "函館市",
		"type"=> "中学校"
	),
	array(
		"id" => "231",
		"url" => "toyone-jh.edumap.jp",
		"organization_id" => "113",
		"organization"=> "豊根村立豊根中学校",
		"school_id"=> "236",
		"school"=> "豊根村立豊根中学校",
		"prefecture_id"=> "23",
		"prefecture"=> "愛知県",
		"city_id"=> "235636",
		"city"=> "豊根村",
		"type"=> "中学校"
	),
	array(
		"id" => "232",
		"url" => "shingohigashi.edumap.jp",
		"organization_id" => "114",
		"organization"=> "川口市立新郷東小学校",
		"school_id"=> "235",
		"school"=> "川口市立新郷東小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112216",
		"city"=> "草加市",
		"type"=> "小学校"
	),
	array(
		"id" => "233",
		"url" => "souya-j.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "243",
		"school"=> "稚内市立宗谷中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "中学校"
	),
	array(
		"id" => "234",
		"url" => "waktonchu-j.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "245",
		"school"=> "稚内市立稚内東中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "中学校"
	),
	array(
		"id" => "235",
		"url" => "masuhoro.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "251",
		"school"=> "稚内市立増幌小中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小中一貫校・義務教育学校"
	),
	array(
		"id" => "236",
		"url" => "wakkanai-tenpokuschool.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "252",
		"school"=> "稚内市立天北小中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小中一貫校・義務教育学校"
	),
	array(
		"id" => "237",
		"url" => "wakkanai-tomiiso-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "240",
		"school"=> "稚内市立富磯小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "238",
		"url" => "wakkanai-koetoi-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "241",
		"school"=> "稚内市立声問小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "239",
		"url" => "nagisanoko-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "244",
		"school"=> "稚内市立宗谷小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "240",
		"url" => "oomisaki-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "246",
		"school"=> "稚内市立大岬小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "241",
		"url" => "wakkanai-minami-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "249",
		"school"=> "稚内市立稚内南小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "242",
		"url" => "wakkanai-higashi-e.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "250",
		"school"=> "稚内市立稚内東小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "243",
		"url" => "wakkanai-minatosyo.edumap.jp",
		"organization_id" => "115",
		"organization"=> "稚内市教育委員会",
		"school_id"=> "254",
		"school"=> "稚内市立稚内港小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012149",
		"city"=> "稚内市",
		"type"=> "小学校"
	),
	array(
		"id" => "244",
		"url" => "usui-h.edumap.jp",
		"organization_id" => "116",
		"organization"=> "福井県立羽水高等学校",
		"school_id"=> "247",
		"school"=> "福井県立羽水高等学校",
		"prefecture_id"=> "18",
		"prefecture"=> "福井県",
		"city_id"=> "182010",
		"city"=> "福井市",
		"type"=> "高等学校"
	),
	array(
		"id" => "245",
		"url" => "c-niiza-daiyon-e.edumap.jp",
		"organization_id" => "117",
		"organization"=> "新座市立第四小学校",
		"school_id"=> "239",
		"school"=> "新座市立第四小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112305",
		"city"=> "新座市",
		"type"=> "小学校"
	),
	array(
		"id" => "246",
		"url" => "okegawa-jh.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "242",
		"school"=> "桶川市立桶川中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "中学校"
	),
	array(
		"id" => "247",
		"url" => "okegawanishi-jh.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "253",
		"school"=> "桶川市立桶川西中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "中学校"
	),
	array(
		"id" => "248",
		"url" => "okegawahigashi-jh.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "256",
		"school"=> "桶川市立桶川東中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "中学校"
	),
	array(
		"id" => "249",
		"url" => "okegawakanou-jh.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "257",
		"school"=> "桶川市立加納中学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "中学校"
	),
	array(
		"id" => "250",
		"url" => "okegawaasahi-es.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "291",
		"school"=> "桶川市立朝日小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "小学校"
	),
	array(
		"id" => "251",
		"url" => "okegawanishi-es.edumap.jp",
		"organization_id" => "118",
		"organization"=> "桶川市教育委員会",
		"school_id"=> "292",
		"school"=> "桶川市立桶川西小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112313",
		"city"=> "桶川市",
		"type"=> "小学校"
	),
	array(
		"id" => "252",
		"url" => "t-araya.edumap.jp",
		"organization_id" => "119",
		"organization"=> "天童市立荒谷小学校",
		"school_id"=> "248",
		"school"=> "天童市立荒谷小学校",
		"prefecture_id"=> "06",
		"prefecture"=> "山形県",
		"city_id"=> "062103",
		"city"=> "天童市",
		"type"=> "小学校"
	),
	array(
		"id" => "253",
		"url" => "mikajima-es.edumap.jp",
		"organization_id" => "120",
		"organization"=> "所沢市立三ケ島小学校",
		"school_id"=> "307",
		"school"=> "所沢市立三ヶ島小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112089",
		"city"=> "所沢市",
		"type"=> "小学校"
	),
	array(
		"id" => "254",
		"url" => "mombetsu-j-mombetsu.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "263",
		"school"=> "紋別市立紋別中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "中学校"
	),
	array(
		"id" => "255",
		"url" => "mombetsu-j-shiomi.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "268",
		"school"=> "紋別市立潮見中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "中学校"
	),
	array(
		"id" => "256",
		"url" => "mombetsu-j-shokotsu.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "269",
		"school"=> "紋別市立渚滑中学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "中学校"
	),
	array(
		"id" => "257",
		"url" => "mombetsu-e-komukai.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "260",
		"school"=> "紋別市立小向小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "258",
		"url" => "mombetsu-e-minamigaoka.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "261",
		"school"=> "紋別市立南丘小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "259",
		"url" => "mombetsu-e-kamishokotsu.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "262",
		"school"=> "紋別市立上渚滑小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "260",
		"url" => "mombetsu-e-shiomi.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "265",
		"school"=> "紋別市立潮見小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "261",
		"url" => "mombetsu-e-shokotsu.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "266",
		"school"=> "紋別市立渚滑小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "262",
		"url" => "mombetsu-e-mombetsu.edumap.jp",
		"organization_id" => "121",
		"organization"=> "紋別市教育委員会",
		"school_id"=> "267",
		"school"=> "紋別市立紋別小学校",
		"prefecture_id"=> "01",
		"prefecture"=> "北海道",
		"city_id"=> "012190",
		"city"=> "紋別市",
		"type"=> "小学校"
	),
	array(
		"id" => "263",
		"url" => "toyone-el.edumap.jp",
		"organization_id" => "122",
		"organization"=> "豊根村立豊根小学校",
		"school_id"=> "264",
		"school"=> "豊根村立豊根小学校",
		"prefecture_id"=> "23",
		"prefecture"=> "愛知県",
		"city_id"=> "235636",
		"city"=> "豊根村",
		"type"=> "小学校"
	),
	array(
		"id" => "264",
		"url" => "nazumi-e.edumap.jp",
		"organization_id" => "123",
		"organization"=> "時津町立鳴鼓小学校",
		"school_id"=> "309",
		"school"=> "時津町立鳴鼓小学校",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "423084",
		"city"=> "時津町",
		"type"=> "小学校"
	),
	array(
		"id" => "265",
		"url" => "ohtawara-city-chikasono-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "276",
		"school"=> "大田原市立親園中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "266",
		"url" => "ohtawara-city-kanedakita-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "277",
		"school"=> "大田原市立金田北中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "267",
		"url" => "ohtawara-city-kanedaminami-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "278",
		"school"=> "大田原市立金田南中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "268",
		"url" => "ohtawara-city-nozaki-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "284",
		"school"=> "大田原市立野崎中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "269",
		"url" => "ohtawara-city-yuzukami-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "285",
		"school"=> "大田原市立湯津上中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "270",
		"url" => "ohtawara-city-ohtawara-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "294",
		"school"=> "大田原市立大田原中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "271",
		"url" => "ohtawara-city-kurobane-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "298",
		"school"=> "大田原市立黒羽中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "272",
		"url" => "ohtawara-city-wakakusa-junior-high-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "301",
		"school"=> "大田原市立若草中学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "中学校"
	),
	array(
		"id" => "273",
		"url" => "ohtawara-city-sakuyama-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "273",
		"school"=> "大田原市立佐久山小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "274",
		"url" => "ohtawara-city-okusawa-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "274",
		"school"=> "大田原市立奥沢小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "275",
		"url" => "ohtawara-city-ryougoutyuuou-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "275",
		"school"=> "大田原市立両郷中央小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "276",
		"url" => "ohtawara-city-sarado-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "279",
		"school"=> "大田原市立佐良土小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "277",
		"url" => "ohtawara-city-kanemaru-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "280",
		"school"=> "大田原市立金丸小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "278",
		"url" => "ohtawara-city-ohtawara-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "281",
		"school"=> "大田原市立大田原小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "279",
		"url" => "ohtawara-city-nishihara-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "282",
		"school"=> "大田原市立西原小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "280",
		"url" => "ohtawara-city-udakawa-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "283",
		"school"=> "大田原市立宇田川小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "281",
		"url" => "ohtawara-city-ichinosawa-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "286",
		"school"=> "大田原市立市野沢小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "282",
		"url" => "ohtawara-city-hiruta-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "289",
		"school"=> "大田原市立蛭田小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "283",
		"url" => "ohtawara-city-sukagawa-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "290",
		"school"=> "大田原市立須賀川小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "284",
		"url" => "ohtawara-city-murasakizuka-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "293",
		"school"=> "大田原市立紫塚小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "285",
		"url" => "ohtawara-city-usuba-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "295",
		"school"=> "大田原市立薄葉小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "286",
		"url" => "ohtawara-city-kawanishi-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "296",
		"school"=> "大田原市立川西小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "287",
		"url" => "ohtawara-city-kurobane-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "297",
		"school"=> "大田原市立黒羽小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "288",
		"url" => "ohtawara-city-handa-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "299",
		"school"=> "大田原市立羽田小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "289",
		"url" => "ohtawara-city-yuzukami-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "300",
		"school"=> "大田原市立湯津上小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "290",
		"url" => "ohtawara-city-ishigami-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "302",
		"school"=> "大田原市立石上小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "291",
		"url" => "ohtawara-city-chikasono-elementary-school.edumap.jp",
		"organization_id" => "124",
		"organization"=> "大田原市教育委員会",
		"school_id"=> "303",
		"school"=> "大田原市立親園小学校",
		"prefecture_id"=> "09",
		"prefecture"=> "栃木県",
		"city_id"=> "092100",
		"city"=> "大田原市",
		"type"=> "小学校"
	),
	array(
		"id" => "292",
		"url" => "mizuho2020.edumap.jp",
		"organization_id" => "125",
		"organization"=> "つがる市立瑞穂小学校",
		"school_id"=> "272",
		"school"=> "つがる市立瑞穂小学校",
		"prefecture_id"=> "02",
		"prefecture"=> "青森県",
		"city_id"=> "022098",
		"city"=> "つがる市",
		"type"=> "小学校"
	),
	array(
		"id" => "293",
		"url" => "togitsukita-e.edumap.jp",
		"organization_id" => "126",
		"organization"=> "時津町立時津北小学校",
		"school_id"=> "311",
		"school"=> "時津町立時津北小学校",
		"prefecture_id"=> "42",
		"prefecture"=> "長崎県",
		"city_id"=> "423084",
		"city"=> "時津町",
		"type"=> "小学校"
	),
	array(
		"id" => "294",
		"url" => "saiwaichosyo.edumap.jp",
		"organization_id" => "127",
		"organization"=> "埼玉県川口市立幸町小学校",
		"school_id"=> "312",
		"school"=> "埼玉県川口市立幸町小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "112038",
		"city"=> "川口市",
		"type"=> "小学校"
	),
	array(
		"id" => "295",
		"url" => "misato-oosawa.edumap.jp",
		"organization_id" => "129",
		"organization"=> "美里町立大沢小学校",
		"school_id"=> "326",
		"school"=> "美里町立大沢小学校",
		"prefecture_id"=> "11",
		"prefecture"=> "埼玉県",
		"city_id"=> "113816",
		"city"=> "美里町",
		"type"=> "小学校"
	),
	array(
		"id" => "296",
		"url" => "oshu-public-elementary-school.edumap.jp",
		"organization_id" => "130",
		"organization"=> "奥州市立人首小学校",
		"school_id"=> "325",
		"school"=> "奥州市立人首小学校",
		"prefecture_id"=> "03",
		"prefecture"=> "岩手県",
		"city_id"=> "032158",
		"city"=> "奥州市",
		"type"=> "小学校"
	),
);
